services:
  - type: web
    name: advanced-api-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend-dev1 && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: streamplus-db
          property: connectionString


databases:
  - name: streamplus-db
    databaseName: streamplus
    user: postgres
    region: oregon
    plan: free

