services:
  - type: web
    name: advanced-api-backend
    runtime: python
    region: oregon
    buildCommand: pip install -r backend-dev1/requirements.txt
    startCommand: uvicorn backend-dev1.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
